export {
  employeeStatusSchema,
  employmentTypeSchema,
  staffDepartmentSchema,
  staffDesignationSchema,
  emergencyContactSchema,
  createEmployeeSchema,
  updateEmployeeSchema,
  deleteEmployeeSchema,
  searchEmployeeSchema,
  type CreateEmployeeInput,
  type UpdateEmployeeInput,
  type DeleteEmployeeInput,
  type SearchEmployeeInput,
} from "./schemas";
