import type {
  SaasSubscriptionStatus,
  SaasFeatureKey,
  BillingCycle,
  InvoiceFoundationStatus,
  UsageMetricKey,
} from "@/types/subscription";

export const SAAS_STATUS_LABELS: Record<SaasSubscriptionStatus, string> = {
  trial: "Trial",
  active: "Active",
  expired: "Expired",
  suspended: "Suspended",
  cancelled: "Cancelled",
  pending: "Pending",
};

export const SAAS_STATUS_VARIANTS: Record<
  SaasSubscriptionStatus,
  "success" | "warning" | "danger" | "secondary" | "info"
> = {
  trial: "info",
  active: "success",
  expired: "danger",
  suspended: "warning",
  cancelled: "secondary",
  pending: "warning",
};

export const BILLING_CYCLE_LABELS: Record<BillingCycle, string> = {
  monthly: "Monthly",
  yearly: "Yearly",
};

export const SAAS_FEATURE_LABELS: Record<SaasFeatureKey, string> = {
  dashboard: "Dashboard",
  orders: "Orders",
  kitchen: "Kitchen",
  billing: "Billing",
  pos: "POS",
  inventory: "Inventory",
  crm: "CRM",
  reports: "Reports",
  staff: "Staff",
  purchases: "Purchases",
  "qr-ordering": "QR Ordering",
  "online-ordering": "Online Ordering",
  "api-access": "API Access",
  "custom-branding": "Custom Branding",
  "advanced-analytics": "Advanced Analytics",
};

export const USAGE_METRIC_LABELS: Record<UsageMetricKey, string> = {
  users: "Users",
  branches: "Branches",
  orders: "Orders",
  storage: "Storage (MB)",
  apiRequests: "API requests",
  menuItems: "Menu items",
  customers: "Customers",
  inventoryItems: "Inventory items",
};

export const INVOICE_STATUS_LABELS: Record<InvoiceFoundationStatus, string> = {
  draft: "Draft",
  open: "Open",
  paid: "Paid",
  void: "Void",
  refunded: "Refunded",
};

export const INVOICE_STATUS_VARIANTS: Record<
  InvoiceFoundationStatus,
  "secondary" | "info" | "success" | "danger" | "warning"
> = {
  draft: "secondary",
  open: "info",
  paid: "success",
  void: "danger",
  refunded: "warning",
};

/** Default catalog used when DB has no plans yet */
export const DEFAULT_PLAN_SEEDS = [
  {
    name: "Free",
    slug: "free",
    description: "Get started with essential restaurant tools.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    currency: "USD",
    trialDays: 14,
    maxBranches: 1,
    maxUsers: 3,
    maxOrdersPerMonth: 200,
    maxMenuItems: 50,
    maxTables: 10,
    storageLimit: 500,
    features: [
      "dashboard",
      "orders",
      "kitchen",
      "billing",
      "reports",
    ] as SaasFeatureKey[],
    isPopular: false,
    isActive: true,
    sortOrder: 10,
  },
  {
    name: "Starter",
    slug: "starter",
    description: "For single-location cafes growing their operations.",
    monthlyPrice: 29,
    yearlyPrice: 290,
    currency: "USD",
    trialDays: 14,
    maxBranches: 1,
    maxUsers: 10,
    maxOrdersPerMonth: 2000,
    maxMenuItems: 200,
    maxTables: 40,
    storageLimit: 2048,
    features: [
      "dashboard",
      "orders",
      "kitchen",
      "billing",
      "pos",
      "inventory",
      "crm",
      "reports",
      "staff",
      "purchases",
    ] as SaasFeatureKey[],
    isPopular: true,
    isActive: true,
    sortOrder: 20,
  },
  {
    name: "Pro",
    slug: "pro",
    description: "Multi-branch ready with advanced analytics.",
    monthlyPrice: 79,
    yearlyPrice: 790,
    currency: "USD",
    trialDays: 14,
    maxBranches: 5,
    maxUsers: 50,
    maxOrdersPerMonth: 20000,
    maxMenuItems: 1000,
    maxTables: 200,
    storageLimit: 10240,
    features: [
      "dashboard",
      "orders",
      "kitchen",
      "billing",
      "pos",
      "inventory",
      "crm",
      "reports",
      "staff",
      "purchases",
      "qr-ordering",
      "online-ordering",
      "custom-branding",
      "advanced-analytics",
    ] as SaasFeatureKey[],
    isPopular: false,
    isActive: true,
    sortOrder: 30,
  },
  {
    name: "Enterprise",
    slug: "enterprise",
    description: "Unlimited scale with API access and full suite.",
    monthlyPrice: 199,
    yearlyPrice: 1990,
    currency: "USD",
    trialDays: 30,
    maxBranches: 100,
    maxUsers: 500,
    maxOrdersPerMonth: 500000,
    maxMenuItems: 10000,
    maxTables: 5000,
    storageLimit: 102400,
    features: [
      "dashboard",
      "orders",
      "kitchen",
      "billing",
      "pos",
      "inventory",
      "crm",
      "reports",
      "staff",
      "purchases",
      "qr-ordering",
      "online-ordering",
      "api-access",
      "custom-branding",
      "advanced-analytics",
    ] as SaasFeatureKey[],
    isPopular: false,
    isActive: true,
    sortOrder: 40,
  },
] as const;
