import type { RbacAction } from "@/types/rbac";

export const RBAC_ACTIONS: readonly RbacAction[] = [
  "view",
  "create",
  "edit",
  "delete",
  "export",
  "import",
  "manage",
  "approve",
  "assign",
  "access",
  "changeStatus",
  "update",
  "complete",
  "refund",
  "print",
  "dashboard",
  "restaurants",
  "users",
  "subscriptions",
  "reports",
  "audit",
  "settings",
  "system",
  "security",
  "printers",
  "devices",
  "branding",
] as const;

export const RBAC_ACTION_LABELS: Record<RbacAction, string> = {
  view: "View",
  create: "Create",
  edit: "Edit",
  delete: "Delete",
  export: "Export",
  import: "Import",
  manage: "Manage",
  approve: "Approve",
  assign: "Assign",
  access: "Access",
  changeStatus: "Change status",
  update: "Update",
  complete: "Complete",
  refund: "Refund",
  print: "Print",
  dashboard: "Dashboard",
  restaurants: "Restaurants",
  users: "Users",
  subscriptions: "Subscriptions",
  reports: "Reports",
  audit: "Audit",
  settings: "Settings",
  system: "System",
  security: "Security",
  printers: "Printers",
  devices: "Devices",
  branding: "Branding",
};
