import type { RbacResource } from "@/types/rbac";

export const RBAC_RESOURCES: readonly RbacResource[] = [
  "dashboard",
  "restaurant",
  "categories",
  "menu-items",
  "tables",
  "orders",
  "kitchen",
  "billing",
  "customers",
  "vendors",
  "purchases",
  "staff",
  "shifts",
  "attendance",
  "reports",
  "analytics",
  "users",
  "roles",
  "settings",
  "subscription",
  "plans",
  "branches",
  "admin",
  "notifications",
  "announcements",
  "activity",
] as const;

export const RBAC_RESOURCE_LABELS: Record<RbacResource, string> = {
  dashboard: "Dashboard",
  restaurant: "Restaurant",
  categories: "Categories",
  "menu-items": "Menu Items",
  tables: "Tables",
  orders: "Orders",
  kitchen: "Kitchen",
  billing: "Billing",
  customers: "Customers",
  vendors: "Vendors",
  purchases: "Purchases",
  staff: "Staff",
  shifts: "Shifts",
  attendance: "Attendance",
  reports: "Reports",
  analytics: "Analytics",
  users: "Users",
  roles: "Roles",
  settings: "Settings",
  subscription: "Subscription",
  plans: "Plans",
  branches: "Branches",
  admin: "Super Admin",
  notifications: "Notifications",
  announcements: "Announcements",
  activity: "Activity",
};
