import type { LucideIcon } from "lucide-react";
import {
  LayoutDashboard,
  FolderTree,
  UtensilsCrossed,
  Table2,
  ClipboardList,
  ChefHat,
  Receipt,
  Users,
  Truck,
  Package,
  UserCog,
  Clock,
  CreditCard,
  BarChart3,
  Settings,
  Store,
  Shield,
  Rocket,
  GitBranch,
  Bell,
  Megaphone,
  Activity,
} from "lucide-react";
import type { RouteConfig } from "@/types/navigation";

export const DASHBOARD_ROUTE_NAME = "dashboard";
export const DASHBOARD_HREF = "/dashboard";

/**
 * Central route registry — single source of truth for paths & metadata.
 * Permission / featureFlag fields are placeholders only.
 */
export const routeRegistry = {
  dashboard: {
    name: "dashboard",
    path: DASHBOARD_HREF,
    icon: LayoutDashboard,
    parent: null,
    children: [],
    description: "Overview of restaurant performance and activity",
    breadcrumbTitle: "Dashboard",
    pageTitle: "Dashboard",
    seoTitle: "Dashboard",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "dashboard",
    permission: { roles: ["super-admin", "restaurant-owner", "manager"] },
    metadata: {
      title: "Dashboard",
      description: "Restaurant operations overview",
      keywords: ["dashboard", "overview", "dineflow"],
      breadcrumbTitle: "Dashboard",
      openGraph: {
        title: "Dashboard",
        description: "Restaurant operations overview",
      },
    },
  },
  categories: {
    name: "categories",
    path: "/categories",
    icon: FolderTree,
    parent: null,
    children: ["categories-new", "categories-detail", "categories-edit"],
    description: "Organize menu categories",
    breadcrumbTitle: "Categories",
    pageTitle: "Categories",
    seoTitle: "Categories",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "restaurant",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["categories.view"],
    },
    metadata: {
      title: "Categories",
      description: "Manage menu categories",
      keywords: ["categories", "menu"],
      breadcrumbTitle: "Categories",
      openGraph: { title: "Categories" },
    },
  },
  "categories-new": {
    name: "categories-new",
    path: "/categories/new",
    icon: FolderTree,
    parent: "categories",
    children: [],
    description: "Create a menu category",
    breadcrumbTitle: "New",
    pageTitle: "New Category",
    seoTitle: "New Category",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["categories.create"] },
    metadata: {
      title: "New Category",
      description: "Create a menu category",
      breadcrumbTitle: "New",
    },
  },
  "categories-detail": {
    name: "categories-detail",
    path: "/categories/[id]",
    icon: FolderTree,
    parent: "categories",
    children: ["categories-edit"],
    description: "Category details",
    breadcrumbTitle: "Details",
    pageTitle: "Category",
    seoTitle: "Category",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["categories.view"] },
    metadata: {
      title: "Category",
      description: "Category details",
      breadcrumbTitle: "Details",
    },
  },
  "categories-edit": {
    name: "categories-edit",
    path: "/categories/[id]/edit",
    icon: FolderTree,
    parent: "categories-detail",
    children: [],
    description: "Edit category",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit Category",
    seoTitle: "Edit Category",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["categories.edit"] },
    metadata: {
      title: "Edit Category",
      description: "Edit menu category",
      breadcrumbTitle: "Edit",
    },
  },
  "menu-items": {
    name: "menu-items",
    path: "/menu-items",
    icon: UtensilsCrossed,
    parent: null,
    children: ["menu-items-new", "menu-items-detail", "menu-items-edit"],
    description: "Manage menu items and pricing",
    breadcrumbTitle: "Menu Items",
    pageTitle: "Menu Items",
    seoTitle: "Menu Items",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "restaurant",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["menu-items.view"],
    },
    metadata: {
      title: "Menu Items",
      description: "Manage restaurant menu items",
      keywords: ["menu", "items"],
      breadcrumbTitle: "Menu Items",
      openGraph: { title: "Menu Items" },
    },
  },
  "menu-items-new": {
    name: "menu-items-new",
    path: "/menu-items/new",
    icon: UtensilsCrossed,
    parent: "menu-items",
    children: [],
    description: "Create a menu item",
    breadcrumbTitle: "New",
    pageTitle: "New Menu Item",
    seoTitle: "New Menu Item",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["menu-items.create"] },
    metadata: {
      title: "New Menu Item",
      description: "Create a menu item",
      breadcrumbTitle: "New",
    },
  },
  "menu-items-detail": {
    name: "menu-items-detail",
    path: "/menu-items/[id]",
    icon: UtensilsCrossed,
    parent: "menu-items",
    children: ["menu-items-edit"],
    description: "Menu item details",
    breadcrumbTitle: "Details",
    pageTitle: "Menu Item",
    seoTitle: "Menu Item",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["menu-items.view"] },
    metadata: {
      title: "Menu Item",
      description: "Menu item details",
      breadcrumbTitle: "Details",
    },
  },
  "menu-items-edit": {
    name: "menu-items-edit",
    path: "/menu-items/[id]/edit",
    icon: UtensilsCrossed,
    parent: "menu-items-detail",
    children: [],
    description: "Edit menu item",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit Menu Item",
    seoTitle: "Edit Menu Item",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["menu-items.edit"] },
    metadata: {
      title: "Edit Menu Item",
      description: "Edit menu item",
      breadcrumbTitle: "Edit",
    },
  },
  tables: {
    name: "tables",
    path: "/tables",
    icon: Table2,
    parent: null,
    children: ["tables-new", "tables-detail", "tables-edit"],
    description: "Floor and table management",
    breadcrumbTitle: "Tables",
    pageTitle: "Tables",
    seoTitle: "Tables",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "restaurant",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager", "waiter"],
      permissions: ["tables.view"],
    },
    metadata: {
      title: "Tables",
      description: "Manage dining tables",
      keywords: ["tables", "floor"],
      breadcrumbTitle: "Tables",
      openGraph: { title: "Tables" },
    },
  },
  "tables-new": {
    name: "tables-new",
    path: "/tables/new",
    icon: Table2,
    parent: "tables",
    children: [],
    description: "Create a dining table",
    breadcrumbTitle: "New",
    pageTitle: "New Table",
    seoTitle: "New Table",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["tables.create"] },
    metadata: {
      title: "New Table",
      description: "Create a dining table",
      breadcrumbTitle: "New",
    },
  },
  "tables-detail": {
    name: "tables-detail",
    path: "/tables/[id]",
    icon: Table2,
    parent: "tables",
    children: ["tables-edit"],
    description: "Table details",
    breadcrumbTitle: "Details",
    pageTitle: "Table",
    seoTitle: "Table",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["tables.view"] },
    metadata: {
      title: "Table",
      description: "Table details",
      breadcrumbTitle: "Details",
    },
  },
  "tables-edit": {
    name: "tables-edit",
    path: "/tables/[id]/edit",
    icon: Table2,
    parent: "tables-detail",
    children: [],
    description: "Edit table",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit Table",
    seoTitle: "Edit Table",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { permissions: ["tables.edit"] },
    metadata: {
      title: "Edit Table",
      description: "Edit dining table",
      breadcrumbTitle: "Edit",
    },
  },
  orders: {
    name: "orders",
    path: "/orders",
    icon: ClipboardList,
    parent: null,
    children: ["orders-new", "orders-detail"],
    description: "Order intake and tracking",
    breadcrumbTitle: "Orders",
    pageTitle: "Orders",
    seoTitle: "Orders",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "operations",
    permission: {
      roles: [
        "super-admin",
        "restaurant-owner",
        "manager",
        "cashier",
        "waiter",
      ],
      permissions: ["orders.view"],
    },
    metadata: {
      title: "Orders",
      description: "Track and manage orders",
      keywords: ["orders"],
      breadcrumbTitle: "Orders",
      openGraph: { title: "Orders" },
    },
  },
  "orders-new": {
    name: "orders-new",
    path: "/orders/new",
    icon: ClipboardList,
    parent: "orders",
    children: [],
    description: "Create an order",
    breadcrumbTitle: "New",
    pageTitle: "New Order",
    seoTitle: "New Order",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "operations",
    permission: { permissions: ["orders.create"] },
    metadata: {
      title: "New Order",
      description: "Create a restaurant order",
      breadcrumbTitle: "New",
    },
  },
  "orders-detail": {
    name: "orders-detail",
    path: "/orders/[id]",
    icon: ClipboardList,
    parent: "orders",
    children: ["orders-edit"],
    description: "Order details",
    breadcrumbTitle: "Details",
    pageTitle: "Order",
    seoTitle: "Order",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "operations",
    permission: { permissions: ["orders.view"] },
    metadata: {
      title: "Order",
      description: "Order details",
      breadcrumbTitle: "Details",
    },
  },
  "orders-edit": {
    name: "orders-edit",
    path: "/orders/[id]/edit",
    icon: ClipboardList,
    parent: "orders-detail",
    children: [],
    description: "Edit order",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit Order",
    seoTitle: "Edit Order",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "operations",
    permission: { permissions: ["orders.edit"] },
    metadata: {
      title: "Edit Order",
      description: "Edit restaurant order",
      breadcrumbTitle: "Edit",
    },
  },
  kitchen: {
    name: "kitchen",
    path: "/kitchen",
    icon: ChefHat,
    parent: null,
    children: ["kitchen-detail"],
    description: "Kitchen display and prep queue",
    breadcrumbTitle: "Kitchen",
    pageTitle: "Kitchen",
    seoTitle: "Kitchen",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "operations",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager", "chef"],
      permissions: ["kitchen.view"],
    },
    metadata: {
      title: "Kitchen",
      description: "Kitchen operations view",
      keywords: ["kitchen", "kds"],
      breadcrumbTitle: "Kitchen",
      openGraph: { title: "Kitchen" },
    },
  },
  "kitchen-detail": {
    name: "kitchen-detail",
    path: "/kitchen/[id]",
    icon: ChefHat,
    parent: "kitchen",
    children: [],
    description: "Kitchen ticket details",
    breadcrumbTitle: "Ticket",
    pageTitle: "Kitchen Ticket",
    seoTitle: "Kitchen Ticket",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "operations",
    permission: { permissions: ["kitchen.view"] },
    metadata: {
      title: "Kitchen Ticket",
      description: "Kitchen order ticket details",
      breadcrumbTitle: "Ticket",
    },
  },
  billing: {
    name: "billing",
    path: "/billing",
    icon: Receipt,
    parent: null,
    children: ["billing-new", "billing-detail"],
    description: "Invoices and payments",
    breadcrumbTitle: "Billing",
    pageTitle: "Billing",
    seoTitle: "Billing",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "operations",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager", "cashier"],
      permissions: ["billing.view"],
    },
    metadata: {
      title: "Billing",
      description: "Billing and payments",
      keywords: ["billing", "payments"],
      breadcrumbTitle: "Billing",
      openGraph: { title: "Billing" },
    },
  },
  "billing-new": {
    name: "billing-new",
    path: "/billing/new",
    icon: Receipt,
    parent: "billing",
    children: [],
    description: "POS terminal",
    breadcrumbTitle: "POS",
    pageTitle: "POS",
    seoTitle: "POS",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "operations",
    permission: { permissions: ["billing.create"] },
    metadata: {
      title: "POS",
      description: "Point of sale terminal",
      breadcrumbTitle: "POS",
    },
  },
  "billing-detail": {
    name: "billing-detail",
    path: "/billing/[id]",
    icon: Receipt,
    parent: "billing",
    children: ["billing-invoice"],
    description: "Bill details",
    breadcrumbTitle: "Details",
    pageTitle: "Bill",
    seoTitle: "Bill",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "operations",
    permission: { permissions: ["billing.view"] },
    metadata: {
      title: "Bill",
      description: "Bill details and payments",
      breadcrumbTitle: "Details",
    },
  },
  "billing-invoice": {
    name: "billing-invoice",
    path: "/billing/[id]/invoice",
    icon: Receipt,
    parent: "billing-detail",
    children: [],
    description: "Invoice preview",
    breadcrumbTitle: "Invoice",
    pageTitle: "Invoice",
    seoTitle: "Invoice",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "operations",
    permission: { permissions: ["billing.view"] },
    metadata: {
      title: "Invoice",
      description: "Invoice and receipt preview",
      breadcrumbTitle: "Invoice",
    },
  },
  customers: {
    name: "customers",
    path: "/customers",
    icon: Users,
    parent: null,
    children: [],
    description: "Customer profiles and history",
    breadcrumbTitle: "Customers",
    pageTitle: "Customers",
    seoTitle: "Customers",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
    },
    metadata: {
      title: "Customers",
      description: "Customer management",
      keywords: ["customers"],
      breadcrumbTitle: "Customers",
      openGraph: { title: "Customers" },
    },
  },
  vendors: {
    name: "vendors",
    path: "/vendors",
    icon: Truck,
    parent: null,
    children: ["vendors-new", "vendors-detail", "vendors-edit"],
    description: "Supplier and vendor management",
    breadcrumbTitle: "Vendors",
    pageTitle: "Vendors",
    seoTitle: "Vendors",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["vendors.view"],
    },
    metadata: {
      title: "Vendors",
      description: "Vendor management",
      keywords: ["vendors", "suppliers"],
      breadcrumbTitle: "Vendors",
      openGraph: { title: "Vendors" },
    },
  },
  "vendors-new": {
    name: "vendors-new",
    path: "/vendors/new",
    icon: Truck,
    parent: "vendors",
    children: [],
    description: "Create vendor",
    breadcrumbTitle: "New",
    pageTitle: "New vendor",
    seoTitle: "New vendor",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["vendors.create"],
    },
    metadata: {
      title: "New vendor",
      description: "Create vendor",
      keywords: ["vendors"],
      breadcrumbTitle: "New",
      openGraph: { title: "New vendor" },
    },
  },
  "vendors-detail": {
    name: "vendors-detail",
    path: "/vendors/[id]",
    icon: Truck,
    parent: "vendors",
    children: ["vendors-edit"],
    description: "Vendor profile",
    breadcrumbTitle: "Details",
    pageTitle: "Vendor",
    seoTitle: "Vendor",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["vendors.view"],
    },
    metadata: {
      title: "Vendor",
      description: "Vendor profile",
      keywords: ["vendors"],
      breadcrumbTitle: "Details",
      openGraph: { title: "Vendor" },
    },
  },
  "vendors-edit": {
    name: "vendors-edit",
    path: "/vendors/[id]/edit",
    icon: Truck,
    parent: "vendors-detail",
    children: [],
    description: "Edit vendor",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit vendor",
    seoTitle: "Edit vendor",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["vendors.edit"],
    },
    metadata: {
      title: "Edit vendor",
      description: "Edit vendor",
      keywords: ["vendors"],
      breadcrumbTitle: "Edit",
      openGraph: { title: "Edit vendor" },
    },
  },
  purchases: {
    name: "purchases",
    path: "/purchases",
    icon: Package,
    parent: null,
    children: ["purchases-new", "purchases-detail", "purchases-edit"],
    description: "Purchase orders and goods receipt",
    breadcrumbTitle: "Purchases",
    pageTitle: "Purchases",
    seoTitle: "Purchases",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["purchases.view"],
    },
    metadata: {
      title: "Purchases",
      description: "Purchase order management",
      keywords: ["purchases", "procurement"],
      breadcrumbTitle: "Purchases",
      openGraph: { title: "Purchases" },
    },
  },
  "purchases-new": {
    name: "purchases-new",
    path: "/purchases/new",
    icon: Package,
    parent: "purchases",
    children: [],
    description: "Create purchase order",
    breadcrumbTitle: "New",
    pageTitle: "New purchase",
    seoTitle: "New purchase",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["purchases.create"],
    },
    metadata: {
      title: "New purchase",
      description: "Create purchase order",
      keywords: ["purchases"],
      breadcrumbTitle: "New",
      openGraph: { title: "New purchase" },
    },
  },
  "purchases-detail": {
    name: "purchases-detail",
    path: "/purchases/[id]",
    icon: Package,
    parent: "purchases",
    children: ["purchases-edit"],
    description: "Purchase details",
    breadcrumbTitle: "Details",
    pageTitle: "Purchase",
    seoTitle: "Purchase",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["purchases.view"],
    },
    metadata: {
      title: "Purchase",
      description: "Purchase details",
      keywords: ["purchases"],
      breadcrumbTitle: "Details",
      openGraph: { title: "Purchase" },
    },
  },
  "purchases-edit": {
    name: "purchases-edit",
    path: "/purchases/[id]/edit",
    icon: Package,
    parent: "purchases-detail",
    children: [],
    description: "Edit purchase order",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit purchase",
    seoTitle: "Edit purchase",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["purchases.edit"],
    },
    metadata: {
      title: "Edit purchase",
      description: "Edit purchase order",
      keywords: ["purchases"],
      breadcrumbTitle: "Edit",
      openGraph: { title: "Edit purchase" },
    },
  },
  staff: {
    name: "staff",
    path: "/staff",
    icon: UserCog,
    parent: null,
    children: ["staff-new", "staff-detail", "staff-edit"],
    description: "Employee directory and staff management",
    breadcrumbTitle: "Staff",
    pageTitle: "Staff",
    seoTitle: "Staff",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["staff.view", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "Staff",
      description: "Staff management",
      keywords: ["staff", "employees", "hr"],
      breadcrumbTitle: "Staff",
      openGraph: { title: "Staff" },
    },
  },
  "staff-new": {
    name: "staff-new",
    path: "/staff/new",
    icon: UserCog,
    parent: "staff",
    children: [],
    description: "Create employee",
    breadcrumbTitle: "New",
    pageTitle: "New employee",
    seoTitle: "New employee",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["staff.create", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "New employee",
      description: "Create employee",
      keywords: ["staff"],
      breadcrumbTitle: "New",
      openGraph: { title: "New employee" },
    },
  },
  "staff-detail": {
    name: "staff-detail",
    path: "/staff/[id]",
    icon: UserCog,
    parent: "staff",
    children: ["staff-edit"],
    description: "Employee profile",
    breadcrumbTitle: "Details",
    pageTitle: "Employee",
    seoTitle: "Employee",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["staff.view", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "Employee",
      description: "Employee profile",
      keywords: ["staff"],
      breadcrumbTitle: "Details",
      openGraph: { title: "Employee" },
    },
  },
  "staff-edit": {
    name: "staff-edit",
    path: "/staff/[id]/edit",
    icon: UserCog,
    parent: "staff-detail",
    children: [],
    description: "Edit employee",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit employee",
    seoTitle: "Edit employee",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["staff.edit", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "Edit employee",
      description: "Edit employee",
      keywords: ["staff"],
      breadcrumbTitle: "Edit",
      openGraph: { title: "Edit employee" },
    },
  },
  shifts: {
    name: "shifts",
    path: "/shifts",
    icon: Clock,
    parent: null,
    children: ["shifts-new", "shifts-detail", "shifts-edit"],
    description: "Shift scheduling and assignment",
    breadcrumbTitle: "Shifts",
    pageTitle: "Shifts",
    seoTitle: "Shifts",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["shifts.view", "staff.view", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "Shifts",
      description: "Shift scheduling",
      keywords: ["shifts", "schedule", "roster"],
      breadcrumbTitle: "Shifts",
      openGraph: { title: "Shifts" },
    },
  },
  "shifts-new": {
    name: "shifts-new",
    path: "/shifts/new",
    icon: Clock,
    parent: "shifts",
    children: [],
    description: "Create shift",
    breadcrumbTitle: "New",
    pageTitle: "New shift",
    seoTitle: "New shift",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["shifts.create", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "New shift",
      description: "Create shift",
      keywords: ["shifts"],
      breadcrumbTitle: "New",
      openGraph: { title: "New shift" },
    },
  },
  "shifts-detail": {
    name: "shifts-detail",
    path: "/shifts/[id]",
    icon: Clock,
    parent: "shifts",
    children: ["shifts-edit"],
    description: "Shift details",
    breadcrumbTitle: "Details",
    pageTitle: "Shift",
    seoTitle: "Shift",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["shifts.view", "staff.view", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "Shift",
      description: "Shift details",
      keywords: ["shifts"],
      breadcrumbTitle: "Details",
      openGraph: { title: "Shift" },
    },
  },
  "shifts-edit": {
    name: "shifts-edit",
    path: "/shifts/[id]/edit",
    icon: Clock,
    parent: "shifts-detail",
    children: [],
    description: "Edit shift",
    breadcrumbTitle: "Edit",
    pageTitle: "Edit shift",
    seoTitle: "Edit shift",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "management",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["shifts.edit", "staff.manage"],
      mode: "any",
    },
    metadata: {
      title: "Edit shift",
      description: "Edit shift",
      keywords: ["shifts"],
      breadcrumbTitle: "Edit",
      openGraph: { title: "Edit shift" },
    },
  },
  reports: {
    name: "reports",
    path: "/reports",
    icon: BarChart3,
    parent: null,
    children: [
      "reports-sales",
      "reports-orders",
      "reports-customers",
      "reports-inventory",
      "reports-purchases",
      "reports-kitchen",
      "reports-staff",
      "reports-payments",
      "reports-taxes",
    ],
    description: "Analytics and reporting",
    breadcrumbTitle: "Reports",
    pageTitle: "Reports",
    seoTitle: "Reports",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view", "analytics.view"],
    },
    metadata: {
      title: "Reports",
      description: "Business reports and analytics",
      keywords: ["reports", "analytics"],
      breadcrumbTitle: "Reports",
      openGraph: { title: "Reports" },
    },
  },
  "reports-sales": {
    name: "reports-sales",
    path: "/reports/sales",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Sales report",
    breadcrumbTitle: "Sales",
    pageTitle: "Sales report",
    seoTitle: "Sales report",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Sales report",
      description: "Sales analytics",
      keywords: ["reports", "sales"],
      breadcrumbTitle: "Sales",
      openGraph: { title: "Sales report" },
    },
  },
  "reports-orders": {
    name: "reports-orders",
    path: "/reports/orders",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Orders report",
    breadcrumbTitle: "Orders",
    pageTitle: "Orders report",
    seoTitle: "Orders report",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Orders report",
      description: "Orders analytics",
      keywords: ["reports", "orders"],
      breadcrumbTitle: "Orders",
      openGraph: { title: "Orders report" },
    },
  },
  "reports-customers": {
    name: "reports-customers",
    path: "/reports/customers",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Customer report",
    breadcrumbTitle: "Customers",
    pageTitle: "Customer report",
    seoTitle: "Customer report",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Customer report",
      description: "Customer analytics",
      keywords: ["reports", "customers"],
      breadcrumbTitle: "Customers",
      openGraph: { title: "Customer report" },
    },
  },
  "reports-inventory": {
    name: "reports-inventory",
    path: "/reports/inventory",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Inventory report",
    breadcrumbTitle: "Inventory",
    pageTitle: "Inventory report",
    seoTitle: "Inventory report",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Inventory report",
      description: "Inventory analytics",
      keywords: ["reports", "inventory"],
      breadcrumbTitle: "Inventory",
      openGraph: { title: "Inventory report" },
    },
  },
  "reports-purchases": {
    name: "reports-purchases",
    path: "/reports/purchases",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Purchase report",
    breadcrumbTitle: "Purchases",
    pageTitle: "Purchase report",
    seoTitle: "Purchase report",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Purchase report",
      description: "Purchase analytics",
      keywords: ["reports", "purchases"],
      breadcrumbTitle: "Purchases",
      openGraph: { title: "Purchase report" },
    },
  },
  "reports-kitchen": {
    name: "reports-kitchen",
    path: "/reports/kitchen",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Kitchen report",
    breadcrumbTitle: "Kitchen",
    pageTitle: "Kitchen report",
    seoTitle: "Kitchen report",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Kitchen report",
      description: "Kitchen analytics",
      keywords: ["reports", "kitchen"],
      breadcrumbTitle: "Kitchen",
      openGraph: { title: "Kitchen report" },
    },
  },
  "reports-staff": {
    name: "reports-staff",
    path: "/reports/staff",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Staff report",
    breadcrumbTitle: "Staff",
    pageTitle: "Staff report",
    seoTitle: "Staff report",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Staff report",
      description: "Staff analytics",
      keywords: ["reports", "staff"],
      breadcrumbTitle: "Staff",
      openGraph: { title: "Staff report" },
    },
  },
  "reports-payments": {
    name: "reports-payments",
    path: "/reports/payments",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Payment summary",
    breadcrumbTitle: "Payments",
    pageTitle: "Payment summary",
    seoTitle: "Payment summary",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Payment summary",
      description: "Payment analytics",
      keywords: ["reports", "payments"],
      breadcrumbTitle: "Payments",
      openGraph: { title: "Payment summary" },
    },
  },
  "reports-taxes": {
    name: "reports-taxes",
    path: "/reports/taxes",
    icon: BarChart3,
    parent: "reports",
    children: [],
    description: "Tax summary",
    breadcrumbTitle: "Taxes",
    pageTitle: "Tax summary",
    seoTitle: "Tax summary",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "reports",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["reports.view"],
    },
    metadata: {
      title: "Tax summary",
      description: "Tax analytics",
      keywords: ["reports", "taxes"],
      breadcrumbTitle: "Taxes",
      openGraph: { title: "Tax summary" },
    },
  },
  subscription: {
    name: "subscription",
    path: "/subscription",
    icon: CreditCard,
    parent: null,
    children: [
      "subscription-plans",
      "subscription-billing",
      "subscription-usage",
      "subscription-history",
    ],
    description: "SaaS subscription, license, and usage",
    breadcrumbTitle: "Subscription",
    pageTitle: "Subscription",
    seoTitle: "Subscription",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["subscription.view", "subscription.manage"],
      mode: "any",
    },
    metadata: {
      title: "Subscription",
      description: "Subscription and license management",
      keywords: ["subscription", "plans", "license", "saas"],
      breadcrumbTitle: "Subscription",
      openGraph: { title: "Subscription" },
    },
  },
  "subscription-plans": {
    name: "subscription-plans",
    path: "/subscription/plans",
    icon: CreditCard,
    parent: "subscription",
    children: [],
    description: "Subscription plans",
    breadcrumbTitle: "Plans",
    pageTitle: "Plans",
    seoTitle: "Plans",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["subscription.view", "plans.manage"],
      mode: "any",
    },
    metadata: {
      title: "Plans",
      description: "Subscription plans",
      keywords: ["subscription", "plans"],
      breadcrumbTitle: "Plans",
      openGraph: { title: "Plans" },
    },
  },
  "subscription-billing": {
    name: "subscription-billing",
    path: "/subscription/billing",
    icon: CreditCard,
    parent: "subscription",
    children: [],
    description: "Subscription billing",
    breadcrumbTitle: "Billing",
    pageTitle: "Subscription billing",
    seoTitle: "Subscription billing",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["subscription.view", "subscription.manage", "billing.manage"],
      mode: "any",
    },
    metadata: {
      title: "Subscription billing",
      description: "Invoices and billing foundation",
      keywords: ["subscription", "billing", "invoices"],
      breadcrumbTitle: "Billing",
      openGraph: { title: "Subscription billing" },
    },
  },
  "subscription-usage": {
    name: "subscription-usage",
    path: "/subscription/usage",
    icon: CreditCard,
    parent: "subscription",
    children: [],
    description: "Usage metrics",
    breadcrumbTitle: "Usage",
    pageTitle: "Usage",
    seoTitle: "Usage",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["subscription.view", "subscription.manage"],
      mode: "any",
    },
    metadata: {
      title: "Usage",
      description: "Tenant usage metrics",
      keywords: ["subscription", "usage"],
      breadcrumbTitle: "Usage",
      openGraph: { title: "Usage" },
    },
  },
  "subscription-history": {
    name: "subscription-history",
    path: "/subscription/history",
    icon: CreditCard,
    parent: "subscription",
    children: [],
    description: "Subscription history",
    breadcrumbTitle: "History",
    pageTitle: "Subscription history",
    seoTitle: "Subscription history",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["subscription.view", "subscription.manage"],
      mode: "any",
    },
    metadata: {
      title: "Subscription history",
      description: "Renewals and invoice history",
      keywords: ["subscription", "history"],
      breadcrumbTitle: "History",
      openGraph: { title: "Subscription history" },
    },
  },
  notifications: {
    name: "notifications",
    path: "/notifications",
    icon: Bell,
    parent: null,
    children: [
      "notifications-preferences",
      "notifications-history",
    ],
    description: "In-app notification center and inbox",
    breadcrumbTitle: "Notifications",
    pageTitle: "Notifications",
    seoTitle: "Notifications",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: [
        "super-admin",
        "restaurant-owner",
        "manager",
        "cashier",
        "chef",
        "waiter",
      ],
      permissions: ["notifications.view", "notifications.manage"],
      mode: "any",
    },
    metadata: {
      title: "Notifications",
      description: "Notification center",
      keywords: ["notifications", "inbox", "alerts"],
      breadcrumbTitle: "Notifications",
      openGraph: { title: "Notifications" },
    },
  },
  "notifications-preferences": {
    name: "notifications-preferences",
    path: "/notifications/preferences",
    icon: Bell,
    parent: "notifications",
    children: [],
    description: "Notification channel and category preferences",
    breadcrumbTitle: "Preferences",
    pageTitle: "Notification preferences",
    seoTitle: "Notification preferences",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: [
        "super-admin",
        "restaurant-owner",
        "manager",
        "cashier",
        "chef",
        "waiter",
        "customer",
      ],
      permissions: [
        "notifications.settings",
        "notifications.view",
        "notifications.manage",
      ],
      mode: "any",
    },
    metadata: {
      title: "Notification preferences",
      description: "Manage notification preferences",
      keywords: ["notifications", "preferences"],
      breadcrumbTitle: "Preferences",
      openGraph: { title: "Notification preferences" },
    },
  },
  "notifications-history": {
    name: "notifications-history",
    path: "/notifications/history",
    icon: Bell,
    parent: "notifications",
    children: [],
    description: "Historical notifications",
    breadcrumbTitle: "History",
    pageTitle: "Notification history",
    seoTitle: "Notification history",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: [
        "super-admin",
        "restaurant-owner",
        "manager",
        "cashier",
        "chef",
        "waiter",
      ],
      permissions: ["notifications.view", "notifications.manage"],
      mode: "any",
    },
    metadata: {
      title: "Notification history",
      description: "Past notifications",
      keywords: ["notifications", "history"],
      breadcrumbTitle: "History",
      openGraph: { title: "Notification history" },
    },
  },
  announcements: {
    name: "announcements",
    path: "/announcements",
    icon: Megaphone,
    parent: null,
    children: [],
    description: "System and restaurant announcements",
    breadcrumbTitle: "Announcements",
    pageTitle: "Announcements",
    seoTitle: "Announcements",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["notifications.view", "announcements.manage"],
      mode: "any",
    },
    metadata: {
      title: "Announcements",
      description: "Announcement center",
      keywords: ["announcements", "notices"],
      breadcrumbTitle: "Announcements",
      openGraph: { title: "Announcements" },
    },
  },
  activity: {
    name: "activity",
    path: "/activity",
    icon: Activity,
    parent: null,
    children: [],
    description: "Restaurant activity feed and event timeline",
    breadcrumbTitle: "Activity",
    pageTitle: "Activity",
    seoTitle: "Activity",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: [
        "super-admin",
        "restaurant-owner",
        "manager",
        "cashier",
        "chef",
        "waiter",
      ],
      permissions: ["activity.view"],
    },
    metadata: {
      title: "Activity",
      description: "Activity feed",
      keywords: ["activity", "timeline", "events"],
      breadcrumbTitle: "Activity",
      openGraph: { title: "Activity" },
    },
  },
  settings: {
    name: "settings",
    path: "/settings",
    icon: Settings,
    parent: null,
    children: [
      "settings-restaurant",
      "settings-business",
      "settings-tax",
      "settings-currency",
      "settings-receipt",
      "settings-invoice",
      "settings-printers",
      "settings-devices",
      "settings-notifications",
      "settings-security",
      "settings-branding",
      "settings-preferences",
      "settings-branches",
    ],
    description: "Workspace and preference settings",
    breadcrumbTitle: "Settings",
    pageTitle: "Settings",
    seoTitle: "Settings",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Settings",
      description: "Application settings and preferences",
      keywords: ["settings", "preferences"],
      breadcrumbTitle: "Settings",
      openGraph: { title: "Settings" },
    },
  },
  "settings-restaurant": {
    name: "settings-restaurant",
    path: "/settings/restaurant",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Restaurant identity and contact settings",
    breadcrumbTitle: "Restaurant",
    pageTitle: "Restaurant settings",
    seoTitle: "Restaurant settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Restaurant settings",
      description: "Restaurant settings",
      keywords: ["settings", "restaurant"],
      breadcrumbTitle: "Restaurant",
      openGraph: { title: "Restaurant settings" },
    },
  },
  "settings-business": {
    name: "settings-business",
    path: "/settings/business",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Legal and business compliance settings",
    breadcrumbTitle: "Business",
    pageTitle: "Business settings",
    seoTitle: "Business settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Business settings",
      description: "Business settings",
      keywords: ["settings", "business", "gst"],
      breadcrumbTitle: "Business",
      openGraph: { title: "Business settings" },
    },
  },
  "settings-tax": {
    name: "settings-tax",
    path: "/settings/tax",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Tax profiles and rounding",
    breadcrumbTitle: "Tax",
    pageTitle: "Tax settings",
    seoTitle: "Tax settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Tax settings",
      description: "Tax settings",
      keywords: ["settings", "tax", "gst"],
      breadcrumbTitle: "Tax",
      openGraph: { title: "Tax settings" },
    },
  },
  "settings-currency": {
    name: "settings-currency",
    path: "/settings/currency",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Currency, timezone, and language",
    breadcrumbTitle: "Currency",
    pageTitle: "Currency settings",
    seoTitle: "Currency settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Currency settings",
      description: "Currency and timezone",
      keywords: ["settings", "currency", "timezone"],
      breadcrumbTitle: "Currency",
      openGraph: { title: "Currency settings" },
    },
  },
  "settings-receipt": {
    name: "settings-receipt",
    path: "/settings/receipt",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Receipt layout and prefixes",
    breadcrumbTitle: "Receipt",
    pageTitle: "Receipt settings",
    seoTitle: "Receipt settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Receipt settings",
      description: "Receipt settings",
      keywords: ["settings", "receipt"],
      breadcrumbTitle: "Receipt",
      openGraph: { title: "Receipt settings" },
    },
  },
  "settings-invoice": {
    name: "settings-invoice",
    path: "/settings/invoice",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Invoice numbering and terms",
    breadcrumbTitle: "Invoice",
    pageTitle: "Invoice settings",
    seoTitle: "Invoice settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Invoice settings",
      description: "Invoice settings",
      keywords: ["settings", "invoice"],
      breadcrumbTitle: "Invoice",
      openGraph: { title: "Invoice settings" },
    },
  },
  "settings-printers": {
    name: "settings-printers",
    path: "/settings/printers",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Printer configuration foundation",
    breadcrumbTitle: "Printers",
    pageTitle: "Printer settings",
    seoTitle: "Printer settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.printers", "settings.manage"],
      mode: "any",
    },
    metadata: {
      title: "Printer settings",
      description: "Printer settings",
      keywords: ["settings", "printers"],
      breadcrumbTitle: "Printers",
      openGraph: { title: "Printer settings" },
    },
  },
  "settings-devices": {
    name: "settings-devices",
    path: "/settings/devices",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Device management foundation",
    breadcrumbTitle: "Devices",
    pageTitle: "Device settings",
    seoTitle: "Device settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.devices", "settings.manage"],
      mode: "any",
    },
    metadata: {
      title: "Device settings",
      description: "Device settings",
      keywords: ["settings", "devices"],
      breadcrumbTitle: "Devices",
      openGraph: { title: "Device settings" },
    },
  },
  "settings-notifications": {
    name: "settings-notifications",
    path: "/settings/notifications",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Operational notification preferences",
    breadcrumbTitle: "Notifications",
    pageTitle: "Notification settings",
    seoTitle: "Notification settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Notification settings",
      description: "Notification settings",
      keywords: ["settings", "notifications"],
      breadcrumbTitle: "Notifications",
      openGraph: { title: "Notification settings" },
    },
  },
  "settings-security": {
    name: "settings-security",
    path: "/settings/security",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Password and session security policies",
    breadcrumbTitle: "Security",
    pageTitle: "Security settings",
    seoTitle: "Security settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.security", "settings.manage"],
      mode: "any",
    },
    metadata: {
      title: "Security settings",
      description: "Security settings",
      keywords: ["settings", "security"],
      breadcrumbTitle: "Security",
      openGraph: { title: "Security settings" },
    },
  },
  "settings-branding": {
    name: "settings-branding",
    path: "/settings/branding",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "Brand colors and logos",
    breadcrumbTitle: "Branding",
    pageTitle: "Branding settings",
    seoTitle: "Branding settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.branding", "settings.manage"],
      mode: "any",
    },
    metadata: {
      title: "Branding settings",
      description: "Branding settings",
      keywords: ["settings", "branding"],
      breadcrumbTitle: "Branding",
      openGraph: { title: "Branding settings" },
    },
  },
  /** Placeholder nested example for future crumbs — not linked in sidebar */
  "settings-preferences": {
    name: "settings-preferences",
    path: "/settings/preferences",
    icon: Settings,
    parent: "settings",
    children: [],
    description: "System and UI preferences",
    breadcrumbTitle: "Preferences",
    pageTitle: "Preferences",
    seoTitle: "Preferences",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: true,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["settings.view", "settings.update", "settings.edit"],
      mode: "any",
    },
    metadata: {
      title: "Preferences",
      description: "System preferences",
      keywords: ["settings", "preferences"],
      breadcrumbTitle: "Preferences",
      openGraph: { title: "Preferences" },
    },
  },
  /** Future admin placeholder — hidden */
  administration: {
    name: "administration",
    path: "/administration",
    icon: Shield,
    parent: null,
    children: [],
    description: "Legacy admin entry — redirects conceptually to /admin",
    breadcrumbTitle: "Administration",
    pageTitle: "Administration",
    seoTitle: "Administration",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.dashboard"] },
    featureFlag: { flag: "admin-console", defaultEnabled: true },
    metadata: {
      title: "Administration",
      description: "Admin console",
      breadcrumbTitle: "Administration",
      openGraph: { title: "Administration" },
    },
  },
  admin: {
    name: "admin",
    path: "/admin",
    icon: Shield,
    parent: null,
    children: [
      "admin-dashboard",
      "admin-restaurants",
      "admin-users",
      "admin-subscriptions",
      "admin-plans",
      "admin-revenue",
      "admin-reports",
      "admin-system",
      "admin-audit",
      "admin-settings",
    ],
    description: "Super Admin platform control panel",
    breadcrumbTitle: "Admin",
    pageTitle: "Super Admin",
    seoTitle: "Super Admin",
    showInNavigation: true,
    showInSidebar: true,
    showInTabs: true,
    group: "administration",
    permission: {
      roles: ["super-admin"],
      permissions: ["admin.dashboard"],
      mode: "any",
    },
    featureFlag: { flag: "admin-console", defaultEnabled: true },
    metadata: {
      title: "Super Admin",
      description: "Platform administration",
      keywords: ["admin", "tenants", "saas"],
      breadcrumbTitle: "Admin",
      openGraph: { title: "Super Admin" },
    },
  },
  "admin-dashboard": {
    name: "admin-dashboard",
    path: "/admin/dashboard",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Admin dashboard",
    breadcrumbTitle: "Dashboard",
    pageTitle: "Admin dashboard",
    seoTitle: "Admin dashboard",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.dashboard"] },
    metadata: {
      title: "Admin dashboard",
      description: "Platform dashboard",
      breadcrumbTitle: "Dashboard",
    },
  },
  "admin-restaurants": {
    name: "admin-restaurants",
    path: "/admin/restaurants",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Tenant restaurants",
    breadcrumbTitle: "Restaurants",
    pageTitle: "Admin restaurants",
    seoTitle: "Admin restaurants",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.restaurants"] },
    metadata: {
      title: "Admin restaurants",
      description: "Tenant management",
      breadcrumbTitle: "Restaurants",
    },
  },
  "admin-users": {
    name: "admin-users",
    path: "/admin/users",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Platform users",
    breadcrumbTitle: "Users",
    pageTitle: "Admin users",
    seoTitle: "Admin users",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.users"] },
    metadata: {
      title: "Admin users",
      description: "User management",
      breadcrumbTitle: "Users",
    },
  },
  "admin-subscriptions": {
    name: "admin-subscriptions",
    path: "/admin/subscriptions",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Subscriptions",
    breadcrumbTitle: "Subscriptions",
    pageTitle: "Admin subscriptions",
    seoTitle: "Admin subscriptions",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: {
      roles: ["super-admin"],
      permissions: ["admin.subscriptions"],
    },
    metadata: {
      title: "Admin subscriptions",
      description: "Subscription management",
      breadcrumbTitle: "Subscriptions",
    },
  },
  "admin-plans": {
    name: "admin-plans",
    path: "/admin/plans",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Plans catalog",
    breadcrumbTitle: "Plans",
    pageTitle: "Admin plans",
    seoTitle: "Admin plans",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: {
      roles: ["super-admin"],
      permissions: ["admin.subscriptions"],
    },
    metadata: {
      title: "Admin plans",
      description: "Plan catalog",
      breadcrumbTitle: "Plans",
    },
  },
  "admin-revenue": {
    name: "admin-revenue",
    path: "/admin/revenue",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Revenue dashboard",
    breadcrumbTitle: "Revenue",
    pageTitle: "Admin revenue",
    seoTitle: "Admin revenue",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.reports"] },
    metadata: {
      title: "Admin revenue",
      description: "Revenue dashboard",
      breadcrumbTitle: "Revenue",
    },
  },
  "admin-reports": {
    name: "admin-reports",
    path: "/admin/reports",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Global reports",
    breadcrumbTitle: "Reports",
    pageTitle: "Admin reports",
    seoTitle: "Admin reports",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.reports"] },
    metadata: {
      title: "Admin reports",
      description: "Global reports",
      breadcrumbTitle: "Reports",
    },
  },
  "admin-system": {
    name: "admin-system",
    path: "/admin/system",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "System health",
    breadcrumbTitle: "System",
    pageTitle: "System health",
    seoTitle: "System health",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.system"] },
    metadata: {
      title: "System health",
      description: "System health",
      breadcrumbTitle: "System",
    },
  },
  "admin-audit": {
    name: "admin-audit",
    path: "/admin/audit",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Audit logs",
    breadcrumbTitle: "Audit",
    pageTitle: "Audit logs",
    seoTitle: "Audit logs",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.audit"] },
    metadata: {
      title: "Audit logs",
      description: "Audit logs",
      breadcrumbTitle: "Audit",
    },
  },
  "admin-settings": {
    name: "admin-settings",
    path: "/admin/settings",
    icon: Shield,
    parent: "admin",
    children: [],
    description: "Admin settings",
    breadcrumbTitle: "Settings",
    pageTitle: "Admin settings",
    seoTitle: "Admin settings",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "administration",
    permission: { roles: ["super-admin"], permissions: ["admin.settings"] },
    metadata: {
      title: "Admin settings",
      description: "Feature flags",
      breadcrumbTitle: "Settings",
    },
  },
  /** Restaurant context placeholder — not a page */
  restaurant: {
    name: "restaurant",
    path: "/restaurant",
    icon: Store,
    parent: null,
    children: ["categories", "menu-items", "tables"],
    description: "Restaurant configuration hub (future)",
    breadcrumbTitle: "Restaurant",
    pageTitle: "Restaurant",
    seoTitle: "Restaurant",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "restaurant",
    permission: { roles: ["super-admin", "restaurant-owner", "manager"] },
    metadata: {
      title: "Restaurant",
      description: "Restaurant hub",
      breadcrumbTitle: "Restaurant",
      openGraph: { title: "Restaurant" },
    },
  },
  /** Restaurant onboarding — authenticated, outside dashboard shell */
  onboarding: {
    name: "onboarding",
    path: "/onboarding",
    icon: Rocket,
    parent: null,
    children: [],
    description: "Restaurant onboarding and tenant setup",
    breadcrumbTitle: "Onboarding",
    pageTitle: "Restaurant Onboarding",
    seoTitle: "Restaurant Onboarding",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
    },
    metadata: {
      title: "Restaurant Onboarding",
      description: "Set up your restaurant workspace",
      keywords: ["onboarding", "restaurant", "tenant"],
      breadcrumbTitle: "Onboarding",
      openGraph: {
        title: "Restaurant Onboarding",
        description: "Set up your restaurant workspace",
      },
    },
  },
  /** Branch / outlet settings hub — hidden from main sidebar */
  "settings-branches": {
    name: "settings-branches",
    path: "/settings/branches",
    icon: GitBranch,
    parent: "settings",
    children: [
      "settings-branches-general",
      "settings-branches-address",
      "settings-branches-hours",
      "settings-branches-branding",
      "settings-branches-taxes",
      "settings-branches-receipt",
      "settings-branches-devices",
    ],
    description: "Branch and outlet management foundation",
    breadcrumbTitle: "Branches",
    pageTitle: "Branches",
    seoTitle: "Branches",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: {
      roles: ["super-admin", "restaurant-owner", "manager"],
      permissions: ["branches.view"],
    },
    metadata: {
      title: "Branches",
      description: "Manage restaurant outlets",
      breadcrumbTitle: "Branches",
      openGraph: { title: "Branches" },
    },
  },
  "settings-branches-general": {
    name: "settings-branches-general",
    path: "/settings/branches/general",
    icon: GitBranch,
    parent: "settings-branches",
    children: [],
    description: "Branch general settings placeholder",
    breadcrumbTitle: "General",
    pageTitle: "Branch General",
    seoTitle: "Branch General",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: { permissions: ["branches.view"] },
    metadata: {
      title: "Branch General",
      description: "Branch identity settings",
      breadcrumbTitle: "General",
    },
  },
  "settings-branches-address": {
    name: "settings-branches-address",
    path: "/settings/branches/address",
    icon: GitBranch,
    parent: "settings-branches",
    children: [],
    description: "Branch address settings placeholder",
    breadcrumbTitle: "Address",
    pageTitle: "Branch Address",
    seoTitle: "Branch Address",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: { permissions: ["branches.view"] },
    metadata: {
      title: "Branch Address",
      description: "Branch location settings",
      breadcrumbTitle: "Address",
    },
  },
  "settings-branches-hours": {
    name: "settings-branches-hours",
    path: "/settings/branches/business-hours",
    icon: GitBranch,
    parent: "settings-branches",
    children: [],
    description: "Branch business hours placeholder",
    breadcrumbTitle: "Business Hours",
    pageTitle: "Branch Business Hours",
    seoTitle: "Branch Business Hours",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: { permissions: ["branches.view"] },
    metadata: {
      title: "Branch Business Hours",
      description: "Opening hours placeholder",
      breadcrumbTitle: "Business Hours",
    },
  },
  "settings-branches-branding": {
    name: "settings-branches-branding",
    path: "/settings/branches/branding",
    icon: GitBranch,
    parent: "settings-branches",
    children: [],
    description: "Branch branding placeholder",
    breadcrumbTitle: "Branding",
    pageTitle: "Branch Branding",
    seoTitle: "Branch Branding",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: { permissions: ["branches.view"] },
    metadata: {
      title: "Branch Branding",
      description: "Branch branding placeholder",
      breadcrumbTitle: "Branding",
    },
  },
  "settings-branches-taxes": {
    name: "settings-branches-taxes",
    path: "/settings/branches/taxes",
    icon: GitBranch,
    parent: "settings-branches",
    children: [],
    description: "Branch taxes placeholder",
    breadcrumbTitle: "Taxes",
    pageTitle: "Branch Taxes",
    seoTitle: "Branch Taxes",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: { permissions: ["branches.view"] },
    metadata: {
      title: "Branch Taxes",
      description: "Tax configuration placeholder",
      breadcrumbTitle: "Taxes",
    },
  },
  "settings-branches-receipt": {
    name: "settings-branches-receipt",
    path: "/settings/branches/receipt",
    icon: GitBranch,
    parent: "settings-branches",
    children: [],
    description: "Branch receipt placeholder",
    breadcrumbTitle: "Receipt",
    pageTitle: "Branch Receipt",
    seoTitle: "Branch Receipt",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: { permissions: ["branches.view"] },
    metadata: {
      title: "Branch Receipt",
      description: "Receipt settings placeholder",
      breadcrumbTitle: "Receipt",
    },
  },
  "settings-branches-devices": {
    name: "settings-branches-devices",
    path: "/settings/branches/devices",
    icon: GitBranch,
    parent: "settings-branches",
    children: [],
    description: "Branch devices placeholder",
    breadcrumbTitle: "Devices",
    pageTitle: "Branch Devices",
    seoTitle: "Branch Devices",
    showInNavigation: false,
    showInSidebar: false,
    showInTabs: false,
    group: "settings",
    permission: { permissions: ["branches.view"] },
    metadata: {
      title: "Branch Devices",
      description: "Devices placeholder",
      breadcrumbTitle: "Devices",
    },
  },
} as const satisfies Record<string, RouteConfig>;

export type RouteName = keyof typeof routeRegistry;

export const routeList: RouteConfig[] = Object.values(
  routeRegistry
) as RouteConfig[];

export function getRouteIcon(name: RouteName): LucideIcon | undefined {
  return routeRegistry[name].icon;
}
