export {
  customerStatusSchema,
  customerGenderSchema,
  customerAddressSchema,
  customerTagsSchema,
  customerNotesSchema,
  createCustomerSchema,
  updateCustomerSchema,
  deleteCustomerSchema,
  updateCustomerStatusSchema,
  addCustomerNoteSchema,
  searchCustomerSchema,
  type CreateCustomerInput,
  type UpdateCustomerInput,
  type DeleteCustomerInput,
  type UpdateCustomerStatusInput,
  type AddCustomerNoteInput,
  type SearchCustomerInput,
} from "./schemas";
